export const prompts: { [key: string]: string[] } = {
    light: [
        'Send a picture of what is on your desk right now.',
        "Can you show me a picture of what you're currently working on?",
        'Where are you right now? Can you show me a photo of your surroundings?',
        "What's the view from your window like? Send a photo.",
        'Can you show me a picture of your favorite mug or cup?',
        'Do you have any plants in your workspace or home? Can you show me a picture?',
        "What's your favorite piece of artwork in your home or office? Can you share a photo?",
        'Can you show me a picture of your current outfit?',
        "Can you share a picture of your current read or what's on your bookshelf?",
        "What's the most interesting thing you can show me within arm's reach?",
        'Can you show me a picture of your favorite gadget or tech accessory?',
        "What's your favorite spot in your home? Can you share a photo?",
        "What's the last thing you bought online? Can you show me a photo?",
        'Can you show me a picture of your current DIY project?',
        "What's the most unusual thing you have on your desk? Can you share a photo?",
        'Can you show me a picture of your current favorite snack or drink?',
        "What's the most interesting piece of clothing in your closet? Can you show me a photo?",
        'Can you share a photo of your current workspace setup?',
        "What's the most beautiful or interesting place you've been to recently? Can you show me a photo?",
        'Can you show me a picture of your favorite artwork or decor piece in your home or office?',
        'What did you have for breakfast this morning?',
        'Did you try any new foods or drinks this week?',
        'How has your week been going so far?',
        "What's the most interesting thing that happened to you today?",
        "What's the weather been like where you are?",
        'Did you meet any interesting people this week?',
        'Have you discovered any new podcasts or music this week?',
        "What's the most exciting thing you have planned for the upcoming weekend?",
        "What's your favorite thing to do during your downtime?",
        'Did you get any good news this week?',
        'Have you learned anything new this week?',
        'Did you have any memorable conversations with anyone this week?',
        'Have you visited any new places or tried any new experiences this week?',
        'Have you done anything special to take care of yourself this week?',
        'Did you achieve any of your goals this week?',
        "What's the most beautiful thing you saw this week?",
        'Have you been watching any good TV shows or movies lately?',
        "What's something that made you smile or laugh this week?",
        'Did you have any challenges this week? How did you overcome them?',
        "What's the highlight of your week so far?",
    ],
    medium: [
        'What was the most interesting thing you learned or experienced today?',
        'Did you accomplish everything on your to-do list today?',
        'What are your plans for tomorrow?',
        'What was the best part of your day?',
        "Is there anything that's been on your mind lately that you'd like to talk about?",
        'Have you tried anything new recently?',
        'What is your favorite activity to do after a long day?',
        'Have you been following any news or events lately that have caught your attention?',
        'What has been your biggest challenge recently, and how have you been dealing with it?',
        'Have you set any new goals for yourself lately, and if so, how are you working towards them?',
        'Have you ever thought about visiting a different continent? If so, which one and why?',
        "Are there any specific activities or attractions that you've always wanted to experience on a family vacation?",
        'Would you prefer a more relaxing vacation or one that is filled with adventure and exploration?',
        "Is there a particular city or country that you've always dreamed of visiting?",
        'Are there any cultural or historical landmarks that you would like to see and learn about together as a family?',
        'Are there any outdoor activities or sports that you would like to try as a family?',
        'Is there a particular hobby or interest that you would like to pursue together as a family in the future?',
        "Are there any places in your local area or nearby cities that you've been meaning to visit together as a family?",
        'Do you have any special events or milestones coming up that you would like to celebrate together as a family?',
        'Are there any traditions or rituals that you would like to establish as a family for future gatherings and events?',
    ],
    heavy: [
        'What are some of your fondest memories of growing up with your family?',
        'Who has been the most influential family member in your life, and why?',
        'What are some traditions or rituals that your family has that are particularly special to you?',
        'Have there been any significant challenges or hardships that your family has faced together, and how did you overcome them?',
        'How has your relationship with your parents and siblings changed over time?',
        'What is something that you wish you had learned earlier in life about family relationships?',
        'What is the best advice that you have ever received from a family member?',
        'Are there any family secrets or stories that have been passed down through the generations?',
        'What is the most important lesson that you have learned from your family?',
        'How has your family influenced your values and beliefs?',
        'What are some things that you admire or appreciate about each member of your family?',
        "What role does religion or spirituality play in your family's life?",
        'How has your family dynamic changed after marriage or starting a family of your own?',
        'Have you ever experienced a major conflict with a family member, and how did you resolve it?',
        'How do you stay connected and maintain relationships with family members who live far away?',
        'How has your family supported you during challenging times in your life?',
        'Are there any family traditions or rituals that you would like to pass down to future generations?',
        'How has your family influenced your career or education choices?',
        'What is something that you would like to teach your children about family relationships?',
        'How has your understanding of family relationships evolved as you have grown older?',
        'What are the biggest obstacles that are preventing you from achieving your personal goals?',
        'What are the specific steps you need to take to overcome these obstacles and achieve your goals?',
        'Are you willing to make sacrifices or changes in your current lifestyle to achieve your goals?',
        'What specific skills or knowledge do you need to develop to improve yourself in your desired area?',
        'Are there any negative habits or behaviors that you need to break in order to achieve your goals?',
        'How do you plan to stay motivated and committed to your self-improvement goals?',
        'What are the potential consequences of not achieving your self-improvement goals, and how will you handle them?',
        'Are there any external factors or influences that may hinder your progress towards your goals, and how will you handle them?',
        'What kind of support or resources do you need to achieve your goals?',
        'What is your long-term plan for continuing your self-improvement journey beyond your initial goals?',
    ],
};
