AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    kinship

Globals:
    Function:
        Timeout: 3

        Tracing: Active
    Api:
        TracingEnabled: true
Resources:
    SendMessageFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./
            Handler: lambdas/sendMessage.sendMessageHandler
            Runtime: nodejs18.x
            Architectures:
                - x86_64
            Events:
                SendMessageEvent:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt SendMessageQueue.Arn
                        BatchSize: 500
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                Sourcemap: true
                EntryPoints:
                    - lambdas/sendMessage.ts
    ReceiveMessageFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./
            Handler: lambdas/receiveMessage.receiveMessageHandler
            Runtime: nodejs18.x
            Architectures:
                - x86_64
            Events:
                ReceiveMessage:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /receiveMessage
                        Method: post
        Metadata: # Manage esbuild properties
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                Sourcemap: true
                EntryPoints:
                    - lambdas/receiveMessage.ts
    SendMessageQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: send-message-queue

    ApplicationResourceGroup:
        Type: AWS::ResourceGroups::Group
        Properties:
            Name:
                Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
            ResourceQuery:
                Type: CLOUDFORMATION_STACK_1_0
    ApplicationInsightsMonitoring:
        Type: AWS::ApplicationInsights::Application
        Properties:
            ResourceGroupName:
                Ref: ApplicationResourceGroup
            AutoConfigurationEnabled: 'true'
Outputs:
    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    HelloWorldApi:
        Description: API Gateway endpoint URL for Prod stage for Hello World function
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/'
    HelloWorldFunction:
        Description: Hello World Lambda Function ARN
        Value: !GetAtt HelloWorldFunction.Arn
    HelloWorldFunctionIamRole:
        Description: Implicit IAM Role created for Hello World function
        Value: !GetAtt HelloWorldFunctionRole.Arn
